import type { WayfernFingerprintConfig, WayfernOS } from "@/types";

export type HardwarePresetGroupId = "macbook_m" | "mac_mini" | "us_laptop";

export type HardwarePresetId =
  | "macbook_air_m1_13"
  | "macbook_pro_m1_13"
  | "macbook_air_m2_13"
  | "macbook_pro_m2_14"
  | "macbook_pro_m2_16"
  | "macbook_air_m3_13"
  | "macbook_air_m3_15"
  | "macbook_pro_m3_14"
  | "macbook_pro_m3_16"
  | "macbook_pro_m4_16"
  | "mac_mini_intel_2018_6"
  | "mac_mini_intel_2018_8"
  | "mac_mini_m1_2020_8"
  | "mac_mini_m1_2020_16"
  | "mac_mini_m2_2023_8"
  | "mac_mini_m2_2023_16"
  | "mac_mini_m2_pro_2023"
  | "mac_mini_m4_2024_8"
  | "mac_mini_m4_2024_16"
  | "mac_mini_m4_pro_2024"
  | "dell_xps_13"
  | "dell_xps_15"
  | "hp_spectre_x360_14"
  | "lenovo_thinkpad_x1_carbon"
  | "lenovo_thinkpad_t14"
  | "microsoft_surface_laptop_5"
  | "microsoft_surface_laptop_studio_2"
  | "asus_zenbook_14"
  | "acer_swift_14"
  | "lenovo_yoga_7i";

export interface HardwarePreset {
  id: HardwarePresetId;
  group: HardwarePresetGroupId;
  os: WayfernOS;
  labelKey: string;
  config: Partial<WayfernFingerprintConfig>;
}

const HARDWARE_PRESET_KEYS: (keyof WayfernFingerprintConfig)[] = [
  "userAgent",
  "platform",
  "platformVersion",
  "brand",
  "brandVersion",
  "hardwareConcurrency",
  "maxTouchPoints",
  "deviceMemory",
  "screenWidth",
  "screenHeight",
  "screenAvailWidth",
  "screenAvailHeight",
  "screenColorDepth",
  "screenPixelDepth",
  "devicePixelRatio",
  "windowOuterWidth",
  "windowOuterHeight",
  "windowInnerWidth",
  "windowInnerHeight",
  "screenX",
  "screenY",
  "webglVendor",
  "webglRenderer",
  "vendor",
  "productSub",
  "cookieEnabled",
  "pdfViewerEnabled",
  "webdriver",
  "audioSampleRate",
  "audioMaxChannelCount",
];

const macDesktopFingerprint = {
  userAgent:
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
  platform: "MacIntel",
  platformVersion: "14.0.0",
  brand: "Google Chrome",
  brandVersion: "120",
  maxTouchPoints: 0,
  deviceMemory: 8,
  devicePixelRatio: 2,
  screenColorDepth: 24,
  screenPixelDepth: 24,
  windowOuterWidth: 1440,
  windowOuterHeight: 900,
  windowInnerWidth: 1440,
  windowInnerHeight: 821,
  screenX: 0,
  screenY: 0,
  vendor: "Google Inc.",
  productSub: "20030107",
  cookieEnabled: true,
  pdfViewerEnabled: true,
  webdriver: false,
  audioSampleRate: 44100,
  audioMaxChannelCount: 2,
} satisfies Partial<WayfernFingerprintConfig>;

const macBookProfiles = {
  macbook_air_m1_13: {
    ...macDesktopFingerprint,
    hardwareConcurrency: 8,
    screenWidth: 1440,
    screenHeight: 900,
    screenAvailWidth: 1440,
    screenAvailHeight: 860,
    webglVendor: "Apple Inc.",
    webglRenderer: "Apple M1",
  },
  macbook_pro_m1_13: {
    ...macDesktopFingerprint,
    hardwareConcurrency: 8,
    screenWidth: 1440,
    screenHeight: 900,
    screenAvailWidth: 1440,
    screenAvailHeight: 860,
    webglVendor: "Apple Inc.",
    webglRenderer: "Apple M1 Pro",
  },
  macbook_air_m2_13: {
    ...macDesktopFingerprint,
    hardwareConcurrency: 8,
    screenWidth: 1470,
    screenHeight: 956,
    screenAvailWidth: 1470,
    screenAvailHeight: 916,
    webglVendor: "Apple Inc.",
    webglRenderer: "Apple M2",
  },
  macbook_pro_m2_14: {
    ...macDesktopFingerprint,
    hardwareConcurrency: 10,
    deviceMemory: 16,
    screenWidth: 1512,
    screenHeight: 982,
    screenAvailWidth: 1512,
    screenAvailHeight: 942,
    webglVendor: "Apple Inc.",
    webglRenderer: "Apple M2 Pro",
  },
  macbook_pro_m2_16: {
    ...macDesktopFingerprint,
    hardwareConcurrency: 12,
    deviceMemory: 16,
    screenWidth: 1728,
    screenHeight: 1117,
    screenAvailWidth: 1728,
    screenAvailHeight: 1077,
    webglVendor: "Apple Inc.",
    webglRenderer: "Apple M2 Max",
  },
  macbook_air_m3_13: {
    ...macDesktopFingerprint,
    hardwareConcurrency: 8,
    screenWidth: 1470,
    screenHeight: 956,
    screenAvailWidth: 1470,
    screenAvailHeight: 916,
    webglVendor: "Apple Inc.",
    webglRenderer: "Apple M3",
  },
  macbook_air_m3_15: {
    ...macDesktopFingerprint,
    hardwareConcurrency: 10,
    screenWidth: 1512,
    screenHeight: 982,
    screenAvailWidth: 1512,
    screenAvailHeight: 942,
    webglVendor: "Apple Inc.",
    webglRenderer: "Apple M3",
  },
  macbook_pro_m3_14: {
    ...macDesktopFingerprint,
    hardwareConcurrency: 11,
    deviceMemory: 18,
    screenWidth: 1512,
    screenHeight: 982,
    screenAvailWidth: 1512,
    screenAvailHeight: 942,
    webglVendor: "Apple Inc.",
    webglRenderer: "Apple M3 Pro",
  },
  macbook_pro_m3_16: {
    ...macDesktopFingerprint,
    hardwareConcurrency: 14,
    deviceMemory: 36,
    screenWidth: 1728,
    screenHeight: 1117,
    screenAvailWidth: 1728,
    screenAvailHeight: 1077,
    webglVendor: "Apple Inc.",
    webglRenderer: "Apple M3 Max",
  },
  macbook_pro_m4_16: {
    ...macDesktopFingerprint,
    hardwareConcurrency: 14,
    deviceMemory: 24,
    screenWidth: 1728,
    screenHeight: 1117,
    screenAvailWidth: 1728,
    screenAvailHeight: 1077,
    webglVendor: "Apple Inc.",
    webglRenderer: "Apple M4 Pro",
  },
} satisfies Record<string, Partial<WayfernFingerprintConfig>>;

const macMiniProfiles = {
  mac_mini_intel_2018_6: {
    ...macDesktopFingerprint,
    hardwareConcurrency: 6,
    deviceMemory: 8,
    screenWidth: 1920,
    screenHeight: 1080,
    screenAvailWidth: 1920,
    screenAvailHeight: 1040,
    webglVendor: "Intel Inc.",
    webglRenderer: "Intel UHD Graphics 630",
  },
  mac_mini_intel_2018_8: {
    ...macDesktopFingerprint,
    hardwareConcurrency: 8,
    deviceMemory: 8,
    screenWidth: 1920,
    screenHeight: 1080,
    screenAvailWidth: 1920,
    screenAvailHeight: 1040,
    webglVendor: "Intel Inc.",
    webglRenderer: "Intel UHD Graphics 630",
  },
  mac_mini_m1_2020_8: {
    ...macDesktopFingerprint,
    hardwareConcurrency: 8,
    screenWidth: 1920,
    screenHeight: 1080,
    screenAvailWidth: 1920,
    screenAvailHeight: 1040,
    webglVendor: "Apple Inc.",
    webglRenderer: "Apple M1",
  },
  mac_mini_m1_2020_16: {
    ...macDesktopFingerprint,
    hardwareConcurrency: 8,
    deviceMemory: 16,
    screenWidth: 1920,
    screenHeight: 1080,
    screenAvailWidth: 1920,
    screenAvailHeight: 1040,
    webglVendor: "Apple Inc.",
    webglRenderer: "Apple M1",
  },
  mac_mini_m2_2023_8: {
    ...macDesktopFingerprint,
    hardwareConcurrency: 8,
    screenWidth: 1920,
    screenHeight: 1080,
    screenAvailWidth: 1920,
    screenAvailHeight: 1040,
    webglVendor: "Apple Inc.",
    webglRenderer: "Apple M2",
  },
  mac_mini_m2_2023_16: {
    ...macDesktopFingerprint,
    hardwareConcurrency: 10,
    deviceMemory: 16,
    screenWidth: 1920,
    screenHeight: 1080,
    screenAvailWidth: 1920,
    screenAvailHeight: 1040,
    webglVendor: "Apple Inc.",
    webglRenderer: "Apple M2",
  },
  mac_mini_m2_pro_2023: {
    ...macDesktopFingerprint,
    hardwareConcurrency: 12,
    deviceMemory: 16,
    screenWidth: 2560,
    screenHeight: 1440,
    screenAvailWidth: 2560,
    screenAvailHeight: 1400,
    webglVendor: "Apple Inc.",
    webglRenderer: "Apple M2 Pro",
  },
  mac_mini_m4_2024_8: {
    ...macDesktopFingerprint,
    hardwareConcurrency: 10,
    screenWidth: 1920,
    screenHeight: 1080,
    screenAvailWidth: 1920,
    screenAvailHeight: 1040,
    webglVendor: "Apple Inc.",
    webglRenderer: "Apple M4",
  },
  mac_mini_m4_2024_16: {
    ...macDesktopFingerprint,
    hardwareConcurrency: 12,
    deviceMemory: 16,
    screenWidth: 1920,
    screenHeight: 1080,
    screenAvailWidth: 1920,
    screenAvailHeight: 1040,
    webglVendor: "Apple Inc.",
    webglRenderer: "Apple M4",
  },
  mac_mini_m4_pro_2024: {
    ...macDesktopFingerprint,
    hardwareConcurrency: 14,
    deviceMemory: 24,
    screenWidth: 2560,
    screenHeight: 1440,
    screenAvailWidth: 2560,
    screenAvailHeight: 1400,
    webglVendor: "Apple Inc.",
    webglRenderer: "Apple M4 Pro",
  },
} satisfies Record<string, Partial<WayfernFingerprintConfig>>;

const usLaptopProfiles = {
  dell_xps_13: {
    userAgent:
      "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    platform: "Win32",
    platformVersion: "10.0.0",
    brand: "Google Chrome",
    brandVersion: "120",
    hardwareConcurrency: 12,
    maxTouchPoints: 10,
    deviceMemory: 16,
    screenWidth: 1920,
    screenHeight: 1200,
    screenAvailWidth: 1920,
    screenAvailHeight: 1160,
    screenColorDepth: 24,
    screenPixelDepth: 24,
    devicePixelRatio: 1.25,
    windowOuterWidth: 1920,
    windowOuterHeight: 1160,
    windowInnerWidth: 1920,
    windowInnerHeight: 1080,
    screenX: 0,
    screenY: 0,
    webglVendor: "Intel Inc.",
    webglRenderer: "Intel Iris Xe Graphics",
    vendor: "Google Inc.",
    productSub: "20030107",
    cookieEnabled: true,
    pdfViewerEnabled: true,
    webdriver: false,
    audioSampleRate: 48000,
    audioMaxChannelCount: 2,
  },
  dell_xps_15: {
    userAgent:
      "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    platform: "Win32",
    platformVersion: "10.0.0",
    brand: "Google Chrome",
    brandVersion: "120",
    hardwareConcurrency: 14,
    maxTouchPoints: 10,
    deviceMemory: 32,
    screenWidth: 3456,
    screenHeight: 2160,
    screenAvailWidth: 3456,
    screenAvailHeight: 2120,
    screenColorDepth: 24,
    screenPixelDepth: 24,
    devicePixelRatio: 2,
    windowOuterWidth: 3456,
    windowOuterHeight: 2120,
    windowInnerWidth: 1728,
    windowInnerHeight: 1000,
    screenX: 0,
    screenY: 0,
    webglVendor: "Intel Inc.",
    webglRenderer: "Intel Arc Graphics",
    vendor: "Google Inc.",
    productSub: "20030107",
    cookieEnabled: true,
    pdfViewerEnabled: true,
    webdriver: false,
    audioSampleRate: 48000,
    audioMaxChannelCount: 2,
  },
  hp_spectre_x360_14: {
    userAgent:
      "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    platform: "Win32",
    platformVersion: "10.0.0",
    brand: "Google Chrome",
    brandVersion: "120",
    hardwareConcurrency: 10,
    maxTouchPoints: 10,
    deviceMemory: 16,
    screenWidth: 1920,
    screenHeight: 1280,
    screenAvailWidth: 1920,
    screenAvailHeight: 1240,
    screenColorDepth: 24,
    screenPixelDepth: 24,
    devicePixelRatio: 1.5,
    windowOuterWidth: 1920,
    windowOuterHeight: 1240,
    windowInnerWidth: 1920,
    windowInnerHeight: 1160,
    screenX: 0,
    screenY: 0,
    webglVendor: "Intel Inc.",
    webglRenderer: "Intel Iris Xe Graphics",
    vendor: "Google Inc.",
    productSub: "20030107",
    cookieEnabled: true,
    pdfViewerEnabled: true,
    webdriver: false,
    audioSampleRate: 48000,
    audioMaxChannelCount: 2,
  },
  lenovo_thinkpad_x1_carbon: {
    userAgent:
      "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    platform: "Win32",
    platformVersion: "10.0.0",
    brand: "Google Chrome",
    brandVersion: "120",
    hardwareConcurrency: 12,
    maxTouchPoints: 10,
    deviceMemory: 16,
    screenWidth: 1920,
    screenHeight: 1200,
    screenAvailWidth: 1920,
    screenAvailHeight: 1160,
    screenColorDepth: 24,
    screenPixelDepth: 24,
    devicePixelRatio: 1.25,
    windowOuterWidth: 1920,
    windowOuterHeight: 1160,
    windowInnerWidth: 1920,
    windowInnerHeight: 1080,
    screenX: 0,
    screenY: 0,
    webglVendor: "Intel Inc.",
    webglRenderer: "Intel Iris Xe Graphics",
    vendor: "Google Inc.",
    productSub: "20030107",
    cookieEnabled: true,
    pdfViewerEnabled: true,
    webdriver: false,
    audioSampleRate: 48000,
    audioMaxChannelCount: 2,
  },
  lenovo_thinkpad_t14: {
    userAgent:
      "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    platform: "Win32",
    platformVersion: "10.0.0",
    brand: "Google Chrome",
    brandVersion: "120",
    hardwareConcurrency: 8,
    maxTouchPoints: 10,
    deviceMemory: 16,
    screenWidth: 1920,
    screenHeight: 1200,
    screenAvailWidth: 1920,
    screenAvailHeight: 1160,
    screenColorDepth: 24,
    screenPixelDepth: 24,
    devicePixelRatio: 1.25,
    windowOuterWidth: 1920,
    windowOuterHeight: 1160,
    windowInnerWidth: 1920,
    windowInnerHeight: 1080,
    screenX: 0,
    screenY: 0,
    webglVendor: "Intel Inc.",
    webglRenderer: "Intel Iris Xe Graphics",
    vendor: "Google Inc.",
    productSub: "20030107",
    cookieEnabled: true,
    pdfViewerEnabled: true,
    webdriver: false,
    audioSampleRate: 48000,
    audioMaxChannelCount: 2,
  },
  microsoft_surface_laptop_5: {
    userAgent:
      "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    platform: "Win32",
    platformVersion: "10.0.0",
    brand: "Google Chrome",
    brandVersion: "120",
    hardwareConcurrency: 10,
    maxTouchPoints: 10,
    deviceMemory: 16,
    screenWidth: 2256,
    screenHeight: 1504,
    screenAvailWidth: 2256,
    screenAvailHeight: 1464,
    screenColorDepth: 24,
    screenPixelDepth: 24,
    devicePixelRatio: 1.5,
    windowOuterWidth: 2256,
    windowOuterHeight: 1464,
    windowInnerWidth: 2256,
    windowInnerHeight: 1380,
    screenX: 0,
    screenY: 0,
    webglVendor: "Intel Inc.",
    webglRenderer: "Intel Iris Xe Graphics",
    vendor: "Google Inc.",
    productSub: "20030107",
    cookieEnabled: true,
    pdfViewerEnabled: true,
    webdriver: false,
    audioSampleRate: 48000,
    audioMaxChannelCount: 2,
  },
  microsoft_surface_laptop_studio_2: {
    userAgent:
      "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    platform: "Win32",
    platformVersion: "10.0.0",
    brand: "Google Chrome",
    brandVersion: "120",
    hardwareConcurrency: 14,
    maxTouchPoints: 10,
    deviceMemory: 32,
    screenWidth: 2400,
    screenHeight: 1600,
    screenAvailWidth: 2400,
    screenAvailHeight: 1560,
    screenColorDepth: 24,
    screenPixelDepth: 24,
    devicePixelRatio: 1.5,
    windowOuterWidth: 2400,
    windowOuterHeight: 1560,
    windowInnerWidth: 2400,
    windowInnerHeight: 1460,
    screenX: 0,
    screenY: 0,
    webglVendor: "NVIDIA Corporation",
    webglRenderer: "NVIDIA GeForce RTX 4050 Laptop GPU",
    vendor: "Google Inc.",
    productSub: "20030107",
    cookieEnabled: true,
    pdfViewerEnabled: true,
    webdriver: false,
    audioSampleRate: 48000,
    audioMaxChannelCount: 2,
  },
  asus_zenbook_14: {
    userAgent:
      "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    platform: "Win32",
    platformVersion: "10.0.0",
    brand: "Google Chrome",
    brandVersion: "120",
    hardwareConcurrency: 8,
    maxTouchPoints: 10,
    deviceMemory: 16,
    screenWidth: 2880,
    screenHeight: 1800,
    screenAvailWidth: 2880,
    screenAvailHeight: 1760,
    screenColorDepth: 24,
    screenPixelDepth: 24,
    devicePixelRatio: 1.5,
    windowOuterWidth: 2880,
    windowOuterHeight: 1760,
    windowInnerWidth: 2880,
    windowInnerHeight: 1680,
    screenX: 0,
    screenY: 0,
    webglVendor: "Intel Inc.",
    webglRenderer: "Intel Iris Xe Graphics",
    vendor: "Google Inc.",
    productSub: "20030107",
    cookieEnabled: true,
    pdfViewerEnabled: true,
    webdriver: false,
    audioSampleRate: 48000,
    audioMaxChannelCount: 2,
  },
  acer_swift_14: {
    userAgent:
      "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    platform: "Win32",
    platformVersion: "10.0.0",
    brand: "Google Chrome",
    brandVersion: "120",
    hardwareConcurrency: 8,
    maxTouchPoints: 10,
    deviceMemory: 16,
    screenWidth: 1920,
    screenHeight: 1200,
    screenAvailWidth: 1920,
    screenAvailHeight: 1160,
    screenColorDepth: 24,
    screenPixelDepth: 24,
    devicePixelRatio: 1.25,
    windowOuterWidth: 1920,
    windowOuterHeight: 1160,
    windowInnerWidth: 1920,
    windowInnerHeight: 1080,
    screenX: 0,
    screenY: 0,
    webglVendor: "AMD",
    webglRenderer: "AMD Radeon Graphics",
    vendor: "Google Inc.",
    productSub: "20030107",
    cookieEnabled: true,
    pdfViewerEnabled: true,
    webdriver: false,
    audioSampleRate: 48000,
    audioMaxChannelCount: 2,
  },
  lenovo_yoga_7i: {
    userAgent:
      "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    platform: "Win32",
    platformVersion: "10.0.0",
    brand: "Google Chrome",
    brandVersion: "120",
    hardwareConcurrency: 10,
    maxTouchPoints: 10,
    deviceMemory: 16,
    screenWidth: 1920,
    screenHeight: 1200,
    screenAvailWidth: 1920,
    screenAvailHeight: 1160,
    screenColorDepth: 24,
    screenPixelDepth: 24,
    devicePixelRatio: 1.25,
    windowOuterWidth: 1920,
    windowOuterHeight: 1160,
    windowInnerWidth: 1920,
    windowInnerHeight: 1080,
    screenX: 0,
    screenY: 0,
    webglVendor: "Intel Inc.",
    webglRenderer: "Intel Iris Xe Graphics",
    vendor: "Google Inc.",
    productSub: "20030107",
    cookieEnabled: true,
    pdfViewerEnabled: true,
    webdriver: false,
    audioSampleRate: 48000,
    audioMaxChannelCount: 2,
  },
} satisfies Record<string, Partial<WayfernFingerprintConfig>>;

export const HARDWARE_PRESET_GROUPS: {
  id: HardwarePresetGroupId;
  labelKey: string;
}[] = [
  { id: "macbook_m", labelKey: "fingerprint.hardwarePresetGroups.macbookM" },
  { id: "mac_mini", labelKey: "fingerprint.hardwarePresetGroups.macMini" },
  { id: "us_laptop", labelKey: "fingerprint.hardwarePresetGroups.usLaptop" },
];

export const HARDWARE_PRESETS: HardwarePreset[] = [
  {
    id: "macbook_air_m1_13",
    group: "macbook_m",
    os: "macos",
    labelKey: "fingerprint.hardwarePresets.macbookAirM1",
    config: macBookProfiles.macbook_air_m1_13,
  },
  {
    id: "macbook_pro_m1_13",
    group: "macbook_m",
    os: "macos",
    labelKey: "fingerprint.hardwarePresets.macbookProM1",
    config: macBookProfiles.macbook_pro_m1_13,
  },
  {
    id: "macbook_air_m2_13",
    group: "macbook_m",
    os: "macos",
    labelKey: "fingerprint.hardwarePresets.macbookAirM2",
    config: macBookProfiles.macbook_air_m2_13,
  },
  {
    id: "macbook_pro_m2_14",
    group: "macbook_m",
    os: "macos",
    labelKey: "fingerprint.hardwarePresets.macbookProM2_14",
    config: macBookProfiles.macbook_pro_m2_14,
  },
  {
    id: "macbook_pro_m2_16",
    group: "macbook_m",
    os: "macos",
    labelKey: "fingerprint.hardwarePresets.macbookProM2_16",
    config: macBookProfiles.macbook_pro_m2_16,
  },
  {
    id: "macbook_air_m3_13",
    group: "macbook_m",
    os: "macos",
    labelKey: "fingerprint.hardwarePresets.macbookAirM3_13",
    config: macBookProfiles.macbook_air_m3_13,
  },
  {
    id: "macbook_air_m3_15",
    group: "macbook_m",
    os: "macos",
    labelKey: "fingerprint.hardwarePresets.macbookAirM3_15",
    config: macBookProfiles.macbook_air_m3_15,
  },
  {
    id: "macbook_pro_m3_14",
    group: "macbook_m",
    os: "macos",
    labelKey: "fingerprint.hardwarePresets.macbookProM3_14",
    config: macBookProfiles.macbook_pro_m3_14,
  },
  {
    id: "macbook_pro_m3_16",
    group: "macbook_m",
    os: "macos",
    labelKey: "fingerprint.hardwarePresets.macbookProM3_16",
    config: macBookProfiles.macbook_pro_m3_16,
  },
  {
    id: "macbook_pro_m4_16",
    group: "macbook_m",
    os: "macos",
    labelKey: "fingerprint.hardwarePresets.macbookProM4_16",
    config: macBookProfiles.macbook_pro_m4_16,
  },
  {
    id: "mac_mini_intel_2018_6",
    group: "mac_mini",
    os: "macos",
    labelKey: "fingerprint.hardwarePresets.macMiniIntel6",
    config: macMiniProfiles.mac_mini_intel_2018_6,
  },
  {
    id: "mac_mini_intel_2018_8",
    group: "mac_mini",
    os: "macos",
    labelKey: "fingerprint.hardwarePresets.macMiniIntel8",
    config: macMiniProfiles.mac_mini_intel_2018_8,
  },
  {
    id: "mac_mini_m1_2020_8",
    group: "mac_mini",
    os: "macos",
    labelKey: "fingerprint.hardwarePresets.macMiniM1_8",
    config: macMiniProfiles.mac_mini_m1_2020_8,
  },
  {
    id: "mac_mini_m1_2020_16",
    group: "mac_mini",
    os: "macos",
    labelKey: "fingerprint.hardwarePresets.macMiniM1_16",
    config: macMiniProfiles.mac_mini_m1_2020_16,
  },
  {
    id: "mac_mini_m2_2023_8",
    group: "mac_mini",
    os: "macos",
    labelKey: "fingerprint.hardwarePresets.macMiniM2_8",
    config: macMiniProfiles.mac_mini_m2_2023_8,
  },
  {
    id: "mac_mini_m2_2023_16",
    group: "mac_mini",
    os: "macos",
    labelKey: "fingerprint.hardwarePresets.macMiniM2_16",
    config: macMiniProfiles.mac_mini_m2_2023_16,
  },
  {
    id: "mac_mini_m2_pro_2023",
    group: "mac_mini",
    os: "macos",
    labelKey: "fingerprint.hardwarePresets.macMiniM2Pro",
    config: macMiniProfiles.mac_mini_m2_pro_2023,
  },
  {
    id: "mac_mini_m4_2024_8",
    group: "mac_mini",
    os: "macos",
    labelKey: "fingerprint.hardwarePresets.macMiniM4_8",
    config: macMiniProfiles.mac_mini_m4_2024_8,
  },
  {
    id: "mac_mini_m4_2024_16",
    group: "mac_mini",
    os: "macos",
    labelKey: "fingerprint.hardwarePresets.macMiniM4_16",
    config: macMiniProfiles.mac_mini_m4_2024_16,
  },
  {
    id: "mac_mini_m4_pro_2024",
    group: "mac_mini",
    os: "macos",
    labelKey: "fingerprint.hardwarePresets.macMiniM4Pro",
    config: macMiniProfiles.mac_mini_m4_pro_2024,
  },
  {
    id: "dell_xps_13",
    group: "us_laptop",
    os: "windows",
    labelKey: "fingerprint.hardwarePresets.dellXps13",
    config: usLaptopProfiles.dell_xps_13,
  },
  {
    id: "dell_xps_15",
    group: "us_laptop",
    os: "windows",
    labelKey: "fingerprint.hardwarePresets.dellXps15",
    config: usLaptopProfiles.dell_xps_15,
  },
  {
    id: "hp_spectre_x360_14",
    group: "us_laptop",
    os: "windows",
    labelKey: "fingerprint.hardwarePresets.hpSpectreX360_14",
    config: usLaptopProfiles.hp_spectre_x360_14,
  },
  {
    id: "lenovo_thinkpad_x1_carbon",
    group: "us_laptop",
    os: "windows",
    labelKey: "fingerprint.hardwarePresets.thinkpadX1Carbon",
    config: usLaptopProfiles.lenovo_thinkpad_x1_carbon,
  },
  {
    id: "lenovo_thinkpad_t14",
    group: "us_laptop",
    os: "windows",
    labelKey: "fingerprint.hardwarePresets.thinkpadT14",
    config: usLaptopProfiles.lenovo_thinkpad_t14,
  },
  {
    id: "microsoft_surface_laptop_5",
    group: "us_laptop",
    os: "windows",
    labelKey: "fingerprint.hardwarePresets.surfaceLaptop5",
    config: usLaptopProfiles.microsoft_surface_laptop_5,
  },
  {
    id: "microsoft_surface_laptop_studio_2",
    group: "us_laptop",
    os: "windows",
    labelKey: "fingerprint.hardwarePresets.surfaceLaptopStudio2",
    config: usLaptopProfiles.microsoft_surface_laptop_studio_2,
  },
  {
    id: "asus_zenbook_14",
    group: "us_laptop",
    os: "windows",
    labelKey: "fingerprint.hardwarePresets.asusZenbook14",
    config: usLaptopProfiles.asus_zenbook_14,
  },
  {
    id: "acer_swift_14",
    group: "us_laptop",
    os: "windows",
    labelKey: "fingerprint.hardwarePresets.acerSwift14",
    config: usLaptopProfiles.acer_swift_14,
  },
  {
    id: "lenovo_yoga_7i",
    group: "us_laptop",
    os: "windows",
    labelKey: "fingerprint.hardwarePresets.lenovoYoga7i",
    config: usLaptopProfiles.lenovo_yoga_7i,
  },
];

export function applyHardwarePreset(
  currentConfig: WayfernFingerprintConfig,
  presetId: HardwarePresetId,
): WayfernFingerprintConfig {
  const preset = HARDWARE_PRESETS.find((item) => item.id === presetId);
  if (!preset) return currentConfig;

  const nextConfig = { ...currentConfig };
  for (const key of HARDWARE_PRESET_KEYS) {
    delete nextConfig[key];
  }

  return { ...nextConfig, ...preset.config };
}

export function matchHardwarePreset(
  config: WayfernFingerprintConfig,
  os: WayfernOS | undefined,
): HardwarePresetId | null {
  for (const preset of HARDWARE_PRESETS) {
    if (preset.os !== os) continue;
    const entries = Object.entries(preset.config) as [
      keyof WayfernFingerprintConfig,
      unknown,
    ][];
    const matches = entries.every(([key, value]) => config[key] === value);
    if (matches) return preset.id;
  }
  return null;
}
