"use client";

import { invoke } from "@tauri-apps/api/core";
import { useCallback, useEffect, useState } from "react";
import { useTranslation } from "react-i18next";
import { LuChevronDown, LuChevronRight } from "react-icons/lu";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { translateBackendError } from "@/lib/backend-errors";
import { showErrorToast, showSuccessToast } from "@/lib/toast-utils";
import type { AutomationScenario } from "@/types";

interface AutomationScenarioDialogProps {
  isOpen: boolean;
  onClose: () => void;
  /** The scenario being edited, or null to create a new one. */
  scenario: AutomationScenario | null;
  onSaved: () => void | Promise<void>;
}

const EMPTY_STEPS = `[
  { "type": "navigate", "url": "{{start_url}}" },
  { "type": "scroll", "min_steps": 3, "max_steps": 8 },
  { "type": "click_random_link" },
  { "type": "dwell", "min_secs": 120, "max_secs": 120 },
  { "type": "screenshot" },
  { "type": "close_profile" }
]`;

const EMPTY_VARIABLES = `[
  { "name": "start_url", "default": "https://www.wikipedia.org" }
]`;

/**
 * Scenarios are edited as JSON rather than through a step builder: the JSON is
 * the same contract MCP clients author against, so a workflow generated by an
 * agent and one written here are interchangeable.
 */
export function AutomationScenarioDialog({
  isOpen,
  onClose,
  scenario,
  onSaved,
}: AutomationScenarioDialogProps) {
  const { t } = useTranslation();
  const [name, setName] = useState("");
  const [description, setDescription] = useState("");
  const [stepsText, setStepsText] = useState(EMPTY_STEPS);
  const [variablesText, setVariablesText] = useState(EMPTY_VARIABLES);
  const [jsonError, setJsonError] = useState<string | null>(null);
  const [isSaving, setIsSaving] = useState(false);
  const [referenceOpen, setReferenceOpen] = useState(false);
  const [reference, setReference] = useState<string | null>(null);

  useEffect(() => {
    if (!isOpen) return;
    setJsonError(null);
    if (scenario) {
      setName(scenario.name);
      setDescription(scenario.description ?? "");
      setStepsText(JSON.stringify(scenario.steps, null, 2));
      setVariablesText(JSON.stringify(scenario.variables ?? [], null, 2));
    } else {
      setName("");
      setDescription("");
      setStepsText(EMPTY_STEPS);
      setVariablesText(EMPTY_VARIABLES);
    }
  }, [isOpen, scenario]);

  const toggleReference = useCallback(async () => {
    setReferenceOpen((open) => !open);
    if (reference !== null) return;
    try {
      const schema = await invoke<unknown>("get_automation_step_schema");
      setReference(JSON.stringify(schema, null, 2));
    } catch (err) {
      console.error("Failed to load automation step schema:", err);
    }
  }, [reference]);

  const handleSave = useCallback(async () => {
    let steps: unknown;
    let variables: unknown;
    try {
      steps = JSON.parse(stepsText);
      variables = JSON.parse(variablesText || "[]");
    } catch {
      setJsonError(t("automation.editor.invalidJson"));
      return;
    }
    if (!Array.isArray(steps) || !Array.isArray(variables)) {
      setJsonError(t("automation.editor.mustBeArray"));
      return;
    }

    setJsonError(null);
    setIsSaving(true);
    try {
      const payload = {
        id: scenario?.id ?? "",
        name,
        description: description.trim() ? description : null,
        variables,
        steps,
      };

      if (scenario) {
        await invoke("update_automation_scenario", {
          scenarioId: scenario.id,
          scenario: payload,
        });
      } else {
        await invoke("create_automation_scenario", { scenario: payload });
      }

      showSuccessToast(t("automation.scenarioSaved"));
      await onSaved();
      onClose();
    } catch (err) {
      showErrorToast(translateBackendError(t, err));
    } finally {
      setIsSaving(false);
    }
  }, [
    stepsText,
    variablesText,
    name,
    description,
    scenario,
    onSaved,
    onClose,
    t,
  ]);

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className="flex max-h-[85vh] max-w-3xl flex-col">
        <DialogHeader>
          <DialogTitle>
            {scenario
              ? t("automation.editor.editTitle")
              : t("automation.editor.createTitle")}
          </DialogTitle>
          <DialogDescription>
            {t("automation.editor.description")}
          </DialogDescription>
        </DialogHeader>

        <div className="flex min-h-0 flex-1 flex-col gap-4 overflow-y-auto">
          <div className="flex flex-col gap-2">
            <Label htmlFor="automation-name">
              {t("automation.editor.nameLabel")}
            </Label>
            <Input
              id="automation-name"
              value={name}
              onChange={(e) => {
                setName(e.target.value);
              }}
              placeholder={t("automation.editor.namePlaceholder")}
              disabled={isSaving}
            />
          </div>

          <div className="flex flex-col gap-2">
            <Label htmlFor="automation-description">
              {t("automation.editor.descriptionLabel")}
            </Label>
            <Input
              id="automation-description"
              value={description}
              onChange={(e) => {
                setDescription(e.target.value);
              }}
              placeholder={t("automation.editor.descriptionPlaceholder")}
              disabled={isSaving}
            />
          </div>

          <div className="flex flex-col gap-2">
            <Label htmlFor="automation-variables">
              {t("automation.editor.variablesLabel")}
            </Label>
            <p className="text-xs text-muted-foreground">
              {t("automation.editor.variablesHint")}
            </p>
            <Textarea
              id="automation-variables"
              value={variablesText}
              onChange={(e) => {
                setVariablesText(e.target.value);
              }}
              className="min-h-24 font-mono text-xs"
              spellCheck={false}
              disabled={isSaving}
            />
          </div>

          <div className="flex flex-col gap-2">
            <Label htmlFor="automation-steps">
              {t("automation.editor.stepsLabel")}
            </Label>
            <p className="text-xs text-muted-foreground">
              {t("automation.editor.stepsHint")}
            </p>
            <Textarea
              id="automation-steps"
              value={stepsText}
              onChange={(e) => {
                setStepsText(e.target.value);
              }}
              className="min-h-56 font-mono text-xs"
              spellCheck={false}
              disabled={isSaving}
            />
          </div>

          {jsonError && <p className="text-sm text-destructive">{jsonError}</p>}

          <div className="flex flex-col gap-2">
            <Button
              type="button"
              variant="ghost"
              size="sm"
              className="self-start gap-1 px-1 text-muted-foreground"
              onClick={() => {
                void toggleReference();
              }}
            >
              {referenceOpen ? (
                <LuChevronDown className="size-4" />
              ) : (
                <LuChevronRight className="size-4" />
              )}
              {t("automation.editor.referenceTitle")}
            </Button>
            {referenceOpen && (
              <pre className="max-h-64 overflow-auto rounded-md border bg-muted/40 p-3 font-mono text-[11px] leading-relaxed">
                {reference ?? t("common.buttons.loading")}
              </pre>
            )}
          </div>
        </div>

        <DialogFooter>
          <Button variant="outline" onClick={onClose} disabled={isSaving}>
            {t("common.buttons.cancel")}
          </Button>
          <Button
            onClick={() => {
              void handleSave();
            }}
            disabled={isSaving || name.trim().length === 0}
          >
            {t("common.buttons.save")}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
